### ISSUE TITLE
pyOpenSSL

### ISSUE THREAD

**Issue by cdenneen** [tecywiz121/letsencrypt-akamai-dns#1]
trying the following produces a requirement of pyOpenSSL >0.14 but latest p27 is 0.13.1

```
certbot --staging --text --agree-tos --email email@domain.com --expand --renew-by-default --configurator certbot-external-auth:out --certbot-external-auth:out-public-ip-logging-ok -d sub1.domain.com -d sub2.domain.com --preferred-challenges dns --certbot-external-auth:out-handler ./fastdns_hook --certbot-external-auth:out-dehydrated-dns run

Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.19.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 19, in <module>
    from certbot import client
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 11, in <module>
    from acme import client as acme_client
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 34, in <module>
    urllib3.contrib.pyopenssl.inject_into_urllib3()
  File "/usr/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 112, in inject_into_urllib3
    _validate_dependencies_met()
  File "/usr/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 147, in _validate_dependencies_met
    raise ImportError("'pyOpenSSL' module missing required functionality. "
ImportError: 'pyOpenSSL' module missing required functionality. Try upgrading to v0.14 or newer.
```

**Comment by tecywiz121** [comment]
Thanks for taking a look at my hook!

I'm not sure if certbot is compatible, but this tool is designed for use with [dehydrated](https://github.com/lukas2511/dehydrated) (an alternative to certbot.)

Either way, I think you're running into trouble before making it to my hook.
